---
title: "prepping followup"
author: "anjie & gal"
date: "4/14/2022"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(jsonlite)
```

# get the subject id prolific id pariing 
```{r}
# has pairing 
rt_d <- read_csv(here("data/02_processed_data/processed_rt_task_data.csv"))
# has prolific id
p_id <- read_csv(here("data/01_merged_data/merged_data.csv")) %>% 
  filter(trial_type == "survey-text" & grepl("p_id", responses)) %>% 
  select(subject, responses) %>% 
  mutate(prolific_id = map(responses, ~ fromJSON(.) %>% as.data.frame()) %>% unlist()) %>% 
  filter(subject %in% unique(rt_d %>% pull(subject))) %>% 
  select(subject, prolific_id)

#raw dataset tells us the stimuli used in memory and curiosity ratings 
raw_d <- read_csv(here("data/01_merged_data/merged_data.csv"))

  
```


# figure out what stimuli participnats have seen

```{r}
# easiest case for math condition participants
background <- rt_d %>% 
  distinct(subject, trial_type, stimulus_displayed) %>% 
  ungroup() %>% 
  filter(trial_type == "background") %>% 
  group_by(subject, trial_type) %>% 
  summarise(background_stimuli = list(stimulus_displayed))

deviant <- rt_d %>% 
  distinct(subject, trial_type, stimulus_displayed) %>% 
  ungroup() %>% 
  filter(trial_type == "deviant") %>% 
  group_by(subject, trial_type) %>% 
  summarise(deviant_stimuli = list(stimulus_displayed))

json_df <- background %>% 
  left_join(deviant, by = "subject") %>% 
  select(subject, background_stimuli, deviant_stimuli)

# figure out the question stimuli
question_stimuli_set <- raw_d %>% 
  filter(subject %in% unique(rt_d$subject)) %>% 
  filter(stimulus_type == "curiousity" | stimulus_type == "memory_test") %>% 
  select(subject, block_index, question_stimuli) %>% 
   group_by(subject) %>% 
  summarise(question_stimuli = list(question_stimuli))

json_df <- json_df %>% left_join(question_stimuli_set, by = "subject") %>% 
  left_join(p_id, by = "subject") %>% 
  mutate(background_stimuli = paste(shQuote(background_stimuli), collapse = ","), 
         deviant_stimuli = paste(shQuote(deviant_stimuli), collapse = ","), 
         question_stimuli = paste(shQuote(question_stimuli), collapse = ","))

subject_stimuli_json <- jsonlite::toJSON(json_df, pretty=T)

write_csv(json_df, here("prepping_followup/stimuli_pairing.csv"))
write(subject_stimuli_json, here("prepping_followup/subject_stimuli_json.json"))
```

`
```{r}
contatct_tracking_df <- json_df %>% ungroup() %>%  select(prolific_id) %>% mutate(contacted = "") 

contatct_tracking_df_1 <- as.data.frame(tibble(contatct_tracking_df[1:80, ]))
contatct_tracking_df_2 <- contatct_tracking_df[81:180, ]
contatct_tracking_df_3 <- contatct_tracking_df[181:280, ]
contatct_tracking_df_4 <- contatct_tracking_df[281:380, ]

write_csv(contatct_tracking_df_1, here("prepping_followup/participant_tracking_wave1.csv"))
write_csv(contatct_tracking_df_2, here("prepping_followup/participant_tracking_wave2.csv"))
write_csv(contatct_tracking_df_3, here("prepping_followup/participant_tracking_wave3.csv"))
write_csv(contatct_tracking_df_4, here("prepping_followup/participant_tracking_wave4.csv"))


```





