---
title: "01_preprocessing"
author: "anjie"
date: "5/5/2022"
output: html_document
---
```{r}
library(tidyverse)
library(here)
library(jsonlite)

source(here("helper/categorize_stimulus_type.R"))

raw_d <- read_csv(here("data/01_merged_data/merged_data.csv"))
pairing_d <- read_csv(here("data/stimuli_pairing.csv"))
prolifi_d <- read_csv(here("data/prolific.csv"))
```

```{r}
p_id_df <- raw_d %>% 
  filter(grepl("p_id", responses)) %>% 
  select(subject, responses) %>% 
  mutate(responses = map(responses, ~ fromJSON(.) %>% as.data.frame())) %>% 
  unnest(responses)

trial_df <- raw_d %>% 
  filter(stimulus_type == "trial") %>% 
  group_by(subject) %>% 
  mutate(trial_number = row_number()) %>% 
  ungroup() %>% 
  select(subject, trial_number, stimulus_displayed, trial_looking_time) %>% 
  left_join(p_id_df, by = "subject") %>% 
  rowwise() %>% 
  mutate(stimulus_type = categorize_stimulus_type(stimulus_displayed, 
                                                  p_id, 
                                                  pairing_d))

ratings_df <- raw_d %>% 
  filter(trial_type == "survey-likert") %>% 
  select(subject, stimulus, responses) %>% 
  mutate(responses = map(responses, ~ fromJSON(.) %>% as.data.frame())) %>% 
  unnest(responses) %>% 
  rename(rating = Q0) %>% 
  left_join(p_id_df, by = "subject") %>% 
  rowwise() %>% 
  mutate(stimulus_type = categorize_stimulus_type(stimulus, 
                                                  p_id, 
                                                  pairing_d))
```



# trimming 

## prolific finish time exlcusion 

```{r}
prolifi_bound <- prolifi_d %>% 
  summarise(
    median = median(time_taken),
    mad = mad(time_taken), 
    upper = median +3 * mad, 
    lower = median -3 * mad)

prolific_exclude_sbj_p_id <- prolifi_d %>% 
  filter(time_taken > prolifi_bound$upper) %>% 
  pull(participant_id)

prolific_exclude_sbj_id <- p_id_df %>% 
  filter(p_id %in% prolific_exclude_sbj_p_id) %>% 
  pull(subject)
```



## participants based exclusion TBA
```{r}
response_bias_subject <- ratings_df %>% 
  ungroup() %>% 
  group_by(subject, rating) %>% 
  count() %>% 
  filter(n > (20* 0.8)) %>% 
  pull(subject)
```


## trial based exclusion 
```{r}
rt_summary <- trial_df %>% 
  ungroup() %>% 
  summarise(
    median = median(log(trial_looking_time)),
    mad = mad(log(trial_looking_time)), 
    upper = median + 3 * mad, 
    lower = median - 3 * mad)
  
trimmed_trial_df <- trial_df %>% 
  filter(!(log(trial_looking_time) > rt_summary$upper | log(trial_looking_time) < rt_summary$lower))
```


```{r}
clean_rt_df <- trimmed_trial_df %>% 
  filter(!(subject %in% response_bias_subject)) %>% 
  filter(!(subject %in% prolific_exclude_sbj_id)) %>% 
  mutate(complexity = case_when(
    grepl("complex", stimulus_displayed) ~ "complex", 
    grepl("simple",stimulus_displayed) ~ 
      "simple"
  ))

clean_rating_df <- ratings_df %>% 
 filter(!(subject %in% response_bias_subject)) %>% 
  mutate(complexity = case_when(
    grepl("complex", stimulus) ~ "complex", 
    grepl("simple",stimulus) ~ 
      "simple"
  ))
```

```{r}
length(unique(clean_rt_df$subject))
```


# sanity check 
```{r}
clean_rt_df %>% 
  ggplot(aes(x = log(trial_looking_time))) + 
  geom_histogram() 

clean_rt_df %>% 
  ggplot(aes(x = log(trial_looking_time))) + 
  geom_histogram() + 
  facet_wrap(~stimulus_type)
```


# key manipulation

```{r}
clean_rt_df %>% 
  ggplot(aes(x = stimulus_type, 
             y = log(trial_looking_time), 
             color = complexity), 
         group = complexity) + 
  stat_summary(fun.data = "mean_cl_boot") +
  theme_classic()

clean_rt_df %>% 
  ggplot(aes(x = stimulus_type, 
             y = trial_looking_time, 
             color = complexity), 
         group = complexity) + 
  stat_summary(fun.data = "mean_cl_boot") +
  theme_classic()

clean_rating_df %>% 
  ggplot(aes(x = stimulus_type, 
             y = rating, 
             color = complexity), 
         group = complexity) + 
  stat_summary(fun.data = "mean_cl_boot") +
  theme_classic()

```
checking fatigue effect? 

```{r}
clean_rt_df %>% 
  ggplot(aes(x = trial_number, 
             y = log(trial_looking_time), 
             color = complexity) 
       ) + 
  stat_summary(fun.data = "mean_cl_boot", ) +
  theme_classic() + 
  facet_wrap(~stimulus_type)
```
```{r}
clean_rt_df %>% 
  mutate(half = case_when(
    trial_number < 6 ~ "first_half", 
    TRUE ~ "second_half"
  )) %>% 
  ggplot(aes(x = stimulus_type, 
             y = log(trial_looking_time))) + 
  stat_summary(fun.data = "mean_cl_boot") +
  theme_classic() + 
  facet_wrap(~half)
```

# Residuals

```{r}
library(lme4)
model <- lm(log(trial_looking_time) ~ trial_number, data = clean_rt_df)
clean_rt_df$res_lt <- residuals.lm(model)

m_model <- lmer(log(trial_looking_time) ~ trial_number + (1|subject), data = clean_rt_df)
clean_rt_df$m_res_lt <- residuals(m_model)

clean_rt_df %>% 
  ggplot(aes(x = stimulus_type, 
             y = log(res_lt), 
             color = complexity), 
         group = complexity) + 
  stat_summary(fun.data = "mean_cl_boot", 
               position = position_dodge(width = .2)) +
  theme_classic()

clean_rt_df %>% 
  ggplot(aes(x = stimulus_type, 
             y = m_res_lt, 
             color = complexity), 
         group = complexity) + 
  stat_summary(fun.data = "mean_cl_boot", 
               position = position_dodge(width = .2)) +
  theme_classic()
```

# Subsetting

```{r}
remembered_subject <- clean_rating_df %>% 
  group_by(subject, stimulus_type) %>% 
  summarise(mean_ratings = mean(rating)) %>% 
  pivot_wider(names_from = stimulus_type, values_from = mean_ratings) %>% 
  mutate(diff_background_novel = background - novel) %>% 
  filter(diff_background_novel > 1)

clean_rt_df %>% 
  mutate(
    subject_type = case_when(
    subject %in% (remembered_subject$subject) ~ "remembered(diff > 1)",
    TRUE ~ "not_remembered"
  )) %>% 
  ggplot(aes(x = stimulus_type, 
             y = res_lt, 
             color = complexity), 
         group = complexity) + 
  stat_summary(fun.data = "mean_cl_boot", 
               position = position_dodge(width = .2)) +
  theme_classic() + 
  facet_wrap(~subject_type)
```

## just looking at ppl remembered complex? 
```{r}
remembered_complex <- clean_rating_df %>% 
  group_by(subject, stimulus_type, complexity) %>% 
  summarise(mean_ratings = mean(rating)) %>% 
  pivot_wider(names_from = stimulus_type, values_from = mean_ratings) %>% 
  filter(complexity == "complex") %>% 
  mutate(diff_background_novel = background - novel) %>% 
  filter(diff_background_novel > 1)

clean_rt_df %>% 
  mutate(
    subject_type = case_when(
    subject %in% (remembered_complex$subject) ~ "remembered complex",
    TRUE ~ "not_remembered"
  )) %>% 
  ggplot(aes(x = stimulus_type, 
             y = res_lt, 
             color = complexity), 
         group = complexity) + 
  stat_summary(fun.data = "mean_cl_boot", 
               position = position_dodge(width = .2)) +
  theme_classic() + 
  facet_wrap(~subject_type)

```

```{r}

remembered_simple <- clean_rating_df %>% 
  group_by(subject, stimulus_type, complexity) %>% 
  summarise(mean_ratings = mean(rating)) %>% 
  pivot_wider(names_from = stimulus_type, values_from = mean_ratings) %>% 
  filter(complexity == "simple") %>% 
  mutate(diff_background_novel = background - novel) %>% 
  filter(diff_background_novel > 1)

clean_rt_df %>% 
  mutate(
    subject_type = case_when(
    subject %in% (remembered_simple$subject) ~ "remembered simple",
    TRUE ~ "not_remembered"
  )) %>% 
  ggplot(aes(x = stimulus_type, 
             y = res_lt, 
             color = complexity), 
         group = complexity) + 
  stat_summary(fun.data = "mean_cl_boot", 
               position = position_dodge(width = .2)) +
  theme_classic() + 
  facet_wrap(~subject_type)
```



# Correlation 

```{r}
clean_rt_df %>% 
  mutate(
    subject_type = case_when(
    subject %in% (remembered_subject$subject) ~ "remembered(diff > 1)",
    TRUE ~ "not_remembered"
  )) %>% 
  left_join(clean_rating_df %>% rename(stimulus_displayed = stimulus) %>% 
              select(subject, stimulus_displayed, rating), by = 
              c("subject", "stimulus_displayed")) %>% 
  ggplot(aes(x = rating, y = log(trial_looking_time), color = complexity, 
             group = complexity)) + 
  geom_point(alpha = .2) + 
  geom_smooth(method = "lm") + 
  facet_grid(~stimulus_type)

```


