---
title: "baby_analysis"
author: "Gal"
date: "6/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Rmisc)
library(dplyr)
library(here)
library(readxl)
library(janitor)
library(nlme)
```

## load files

```{r, include=FALSE}

# jspsych files
looking_list <- read_excel_allsheets(here::here("data", "output.xlsx"))

# jspsych files
jspsych_files <- list.files("data/jspsych")
setwd(here::here("data", "jspsych"))
jspsych_list <- lapply(jspsych_files, read.csv)

```

## reshape dfs
```{r}
looking_df <- map_dfr(looking_list, ~ .x, .id = 'subject') %>% 
  clean_names() %>% separate(sheet_name, into = c("subject", "coder")) %>%
  mutate(subject = as.numeric(subject), coder = as.numeric(coder))

jspsych_df <- map_dfr(jspsych_list, ~ .x, .id = 'subjectid') 

# get age and gender
age_and_gender <- jspsych_df %>% select(responses) %>%
  filter(responses != "") %>%
  separate(responses, into = c('age', 'gender'), sep=',') %>% 
    separate(age, into = c('del', 'age'), sep=':') %>% 
    separate(gender, into = c('del2', 'gender'), sep=':') %>%
  tidyr::extract(age, "age") %>% tidyr::extract(gender, "gender") %>%
  select(age, gender) %>% dplyr::mutate(subject_id = row_number())

# get trials
trial_df <- jspsych_df %>%
  filter(stimulus_type == 'trial') %>% 
  select(subject, rt, stimulus_displayed, block_number, block_type) %>%
  group_by(subject) %>% dplyr::mutate(subject_id = cur_group_id(),
                                      stimulus_displayed = as.character(stimulus_displayed),
                                      stimulus = str_match(stimulus_displayed, "simple_(.*?)_A.gif")[,2],
                                      stimulus = as.numeric(stimulus)) %>%
  group_by(subject_id, block_number) %>% 
  dplyr::mutate(trial_num = 1:n(),
                valid = case_when(    
                #mark blocks with uneven trial num or less than 4 (ended prematurely)  
                n() %% 2 != 0 ~ FALSE, 
                n() < 4 ~ FALSE,
                TRUE ~ TRUE),
                fam_or_test = case_when( # last trial is test, rest if familiarization
                trial_num < n() ~ 'fam',
                trial_num == n() ~ 'test'
        ),
        fam_duration = max(trial_num) - 1, # how many fam trials in this block
        block_number = block_number + 1) %>%
  group_by(subject_id, block_number, fam_or_test) %>%
  # remove fam trials except last, because this is the format of the looking data (one row for all fam trials)
  dplyr::filter(!(fam_or_test == 'fam' & trial_num < n())) %>%
  ungroup() %>%
  left_join(age_and_gender, by= 'subject_id')  # add age & gender info
  
  
  # check for subjects with missing blocks (when experiment was ended prematurely)
incomplete_subjects <-  trial_df %>% 
                        group_by(subject_id) %>% 
                        dplyr::summarise(count = n_distinct(block_number)) %>% 
                        filter(count<6) %>% 
                        pull(subject_id)

# complete missing blocks (for experiments that ended prematurely)
trial_df <- trial_df %>% complete(subject_id, nesting(block_number, fam_or_test)) %>%
   # make these trials invalid
  # add temp_id
  mutate(valid = case_when(
         is.na(valid) ~ FALSE,
         TRUE ~ valid)) %>%
  slice(rep(1:n(), each = 2))  %>% # duplicate for each coder
  dplyr::mutate(coder = rep_len(c(1,2), n()), 
        temp_id = paste0(subject_id, block_number, fam_or_test, coder)) %>%
  select(-c("coder"))
        

  # check whether column ids
  
# check out subjects who didn't finish study
# View(trial_df %>% filter(subject_id == incomplete_subjects))


# add temp id to looking df
looking_df <- looking_df %>% filter(trial_type != 'a') %>% 
  mutate(
    trial_type = case_when(
                  trial_type == 'f' ~ 'fam',
                  trial_type == 't' ~ 'test'),
  ) %>%
  group_by(subject, trial_type, coder) %>%
  dplyr::mutate(block_number = row_number(),
         temp_id = paste0(subject, block_number, trial_type, coder)) %>%
  dplyr::rename(looking_time_total = looks_on_total_s,
                looking_time_1500 = looks_on_1500_s,
                looking_time_2000 = looks_on_2000_s,
                looking_time_2500 = looks_on_2500_s,
                looking_time_3000 = looks_on_3000_s) %>%
  select(-c("block_number", "x1", "trial_number"))


# join trials and looking times
complete_df <- left_join(looking_df, trial_df, by = 'temp_id')  %>%
  select(-c("temp_id", "subject.x", "subject.y")) %>% 
  group_by(subject_id, block_number, trial_type) %>%
  dplyr::mutate(coder_num = n()) %>% # add column saying how many coders this trial has
  mutate(fam_duration = factor(fam_duration, levels = c(3,5,7))) %>%
  ungroup() %>% group_by(subject_id)

```

# Inter-coder reliability
```{r}
# Correlation
coder_1 <- complete_df %>% filter(coder_num == 2 & coder == 1) %>% pull(looking_time_2000)
coder_2 <- complete_df %>% filter(coder_num == 2 & coder == 2) %>% pull(looking_time_2000)
  
cor(coder_1, coder_2)

# Big discrepancies
coder_df <- complete_df %>% filter(coder_num == 2 & coder == 1)
View(coder_df[abs(coder_1-coder_2) > 5,])

```


# Exclusions

```{r}
# remove outlier looking times


# remove based on looking at familiarization 


```

# Visualize

## Raw data 
```{r}
ggplot(complete_df) + geom_histogram(aes(x=looking_time_2000), bins = 20) + xlab('Looking time in (s)')

```


## Looking time by block number 
```{r pressure, echo=FALSE}
#visualize test looking times
test_df <- complete_df %>% filter(fam_or_test == 'test' & coder == 1) %>% dplyr::group_by(subject_id) %>% 
  dplyr::mutate(normalized_LT = (looking_time_2000-mean(looking_time_2000))/sd(looking_time_2000))


# calculate means
mean_df <- summarySE(test_df, measurevar="looking_time_2000", groupvars=c("block_number"))

ggplot(test_df %>% filter(fam_or_test == 'test'), aes(x=block_number, y = looking_time_2000)) + 
  geom_point(alpha = 0.2) + geom_line(aes(group = subject_id), alpha=0.2) + stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .1))  + stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = .1)) + xlab('Block Number') + ylab('Looking Time (s)') + theme_classic(base_size = 15)
```

## Main effect
```{r}

# calculate means
mean_df <- summarySE(test_df, measurevar="looking_time_2000", groupvars=c("block_type"))

ggplot(test_df, aes(x=block_type, y=looking_time_2000)) + geom_jitter(width = 0.1, alpha = 0.2)  + stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = .1)) + xlab('Test trial type') + ylab('Looking Time (s)') + theme_classic(base_size = 15)
```

## Looking time by familiarization duration
```{r}
# calculate means
mean_df <- summarySE(test_df, measurevar="looking_time_2000", groupvars=c("fam_duration"))

mean_df <- summarySE(test_df, measurevar="looking_time_2000", groupvars=c("fam_duration"))


ggplot(test_df, aes(x=fam_duration, y=looking_time_2000, color = fam_duration)) + geom_jitter(width = 0.1, alpha = 0.2)  + stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = .1)) +  xlab('# of Fam Trials') + ylab('Looking Time (s)') + labs(color = '# of Fam Trials') + theme_grey(base_size = 14) +
  theme(legend.position="none",
        axis.text=element_text(size=15))

```

## Main effect by fam duration
```{r}
# calculate means
mean_df <- summarySE(test_df, measurevar="normalized_LT", groupvars=c("block_type", "fam_duration"))

ggplot(test_df, aes(x=block_type, y=normalized_LT, group=fam_duration, color = fam_duration)) + geom_point(alpha=0.2, position = position_dodge(width = .1)) + 
    stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .1))  + 
  stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = .1)) + facet_wrap(~fam_duration) + xlab('Block number') + ylab('normalized LT') + labs(color = '# of Fam Trials') + theme_classic() + 
  theme(strip.text.x = element_text(size = 14, colour = "black")) + ggtitle('')
  
  
  # geom_point(data=mean_df, aes(x = block_type, y=looking_time_until_lookaway, color = fam_duration), shape=24, size=3, position = position_jitter(width = 0.25, seed = 123)) + geom_errorbar(data=mean_df, aes(ymin=looking_time_until_lookaway-ci/2, ymax=looking_time_until_lookaway+ci/2, color = fam_duration), width=0, size=0.0, position = position_jitter(width = 0.25, seed = 123)) 

```

## order effect? 

```{r}
ggplot(test_df, 
       aes(x=block_number, y=looking_time_2000, group=block_type, color = block_type)) + geom_point(alpha=0.2, position = position_dodge(width = .1))  + 
  stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = .3)) +
  geom_smooth(method = "lm")+
  facet_wrap(~fam_duration)
```
that was not too informative, can we just count how many data point we have in each category? 

```{r}
test_df %>% 
  group_by(block_number, block_type, fam_duration) %>% 
   dplyr::summarize(n_trial = n()) %>% 
  ggplot(aes(x=block_number, y=n_trial, group=block_type, color = block_type)) + 
  geom_point(alpha=.8, position = position_dodge(width = .1))  + 
  geom_line()+
  facet_wrap(~fam_duration)

```


## Models
```{r}
# log transform once figuring out how to deal with 0's
model1 <- lme(log(looking_time_2000+0.01) ~ block_type * fam_duration + block_number, random = ~1|subject_id, data = test_df)
summary(model1)

```


## helper functions
```{r}
read_excel_allsheets <- function(filename, single_frame = TRUE) {
  sheets <- readxl::excel_sheets(filename)
  ldf <- lapply(sheets, function(X) readxl::read_excel(filename, sheet = X))
  names(ldf) <- sheets
  if(single_frame == TRUE){ # Creates a single data frame with all sheets combined together
    ldf <- ldf %>% dplyr::bind_rows(.id = 'sheet_name') %>% tibble::as_tibble()
  } else{ # Creates a separate data frame for each sheet, with each data frame being called the name of that sheet
    list2env(ldf, envir = .GlobalEnv)
  }
  return(ldf)
}

myjit <- ggproto("fixJitter", PositionDodge,
                 width = 0.3,
                 dodge.width = 0.1,
                 jit = NULL,
                 compute_panel =  function (self, data, params, scales) 
                 {

                   #Generate Jitter if not yet
                   if(is.null(self$jit) ) {
                    self$jit <-jitter(rep(0, nrow(data)), amount=self$dodge.width)
                   }

                   data <- ggproto_parent(PositionDodge, self)$compute_panel(data, params, scales)

                   data$x <- data$x + self$jit
                   #For proper error extensions
                   if("xmin" %in% colnames(data)) data$xmin <- data$xmin + self$jit
                   if("xmax" %in% colnames(data)) data$xmax <- data$xmax + self$jit
                   data
                 } )


```