---
title: "exposure_duration_analysis"
author: "gal"
date: '2023-01-18'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)
library(ggforce)
library(pracma)
library(lmerTest)
library(readr)
library(stringr)
```

Load data
```{r}

# data
exp3_data = read.csv('processed_data/after_qc/exp3_data.csv') %>% mutate(experiment = 3)
exp4_data = read.csv('processed_data/after_qc/exp4_data.csv') %>% mutate(experiment = 4) 
exp5_data = read.csv('processed_data/after_qc/exp5_data.csv') %>% mutate(experiment = 5) 


# experimenter manual exclusions
exclusions_exp3 = read.csv('data/exp3/exclusions/exclusions.csv') %>% mutate(experiment = 3)
exclusions_exp4 = read.csv('data/exp4/exclusions/exclusions.csv') %>% mutate(experiment = 4)
exclusions_exp5 = read.csv('data/exp5/exclusions/exclusions.csv') %>% mutate(experiment = 5)

```


Combine datasets & exclusions files
```{r}
common_columns = Reduce(intersect,list(colnames(exp3_data), colnames(exp4_data), colnames(exp5_data)))

data_df = rbind(
  subset(exp3_data, select = common_columns), 
  subset(exp4_data, select = common_columns),
    subset(exp5_data, select = common_columns)
)

exclusions_df =  rbind(exclusions_exp3, exclusions_exp4, exclusions_exp5
                       )

```


Wrangle data df
```{r}

# separate trial type column
data_df %<>% separate(Trials.trialType, sep = '-', into = c('fam_or_test', 'fam_duration', 'test_type')) 

# create block number variable
data_df <- data_df %>% arrange(experiment, SubjectInfo.subjID, Trials.ordinal) %>% group_by(experiment, SubjectInfo.subjID) %>%   mutate(value_change = (fam_duration != lag(fam_duration, default = first(fam_duration))) | 
           (test_type != lag(test_type, default = first(test_type)))) %>% # Create a logical column indicating whether the values changed compared to the previous row
  mutate(block_num = 1 + cumsum(value_change)) %>% # Create a new column 'group_number' by cumulative sum of value_change
  select(-value_change) # Remove the intermediate value_change column

# make fam duration numeric
# data_df %<>% mutate(fam_duration = as.numeric(fam_duration))

data_df %<>% mutate(test_type = case_when(fam_duration == 0 ~ "fam",
                                          test_type == 'background' ~ "fam",
                                           test_type == 'deviant' ~ "nov"))

# rename a bunch of columns
data_df %<>% rename(subject_num = SubjectInfo.subjID, LT = Looks.duration_onLooks, age = SubjectInfo.testAge, sex = SubjectInfo.gender)

# add fam durations to make plots complete
data_df %<>% complete(fam_duration)
```


# Get stimuli & sharing level

```{r}

# jspsych files
jspsych_files_exp3 <- list.files("data/exp3", full.names = T) 
jspsych_list_exp3 <- lapply(jspsych_files_exp3[2:length(jspsych_files_exp3)], read.csv)
jspsych_list_exp3 <- lapply(jspsych_list_exp3, function(x) {x['success'] = NULL; x})
subject_numbers_exp3 = parse_number(str_replace(jspsych_files_exp3[2:length(jspsych_files_exp3)], "data/exp3/",""))
subject_mapping_exp3 <- data.frame(old_subject = as.character(seq(1, length(subject_numbers_exp3))), new_subject = subject_numbers_exp3)
jspsych_df_exp3 <- map_dfr(jspsych_list_exp3, ~ .x, .id = 'subjectid') %>% mutate(experiment = 3) %>% 
  left_join(subject_mapping_exp3, by = c("subjectid" = "old_subject")) %>% select(-subjectid) %>% rename(subjectid = new_subject)

jspsych_files_exp4 <- list.files("data/exp4", full.names = T) 
jspsych_list_exp4 <- lapply(jspsych_files_exp4[2:length(jspsych_files_exp4)], read.csv)
jspsych_list_exp4 <- lapply(jspsych_list_exp4, function(x) {x['success'] = NULL; x})
subject_numbers_exp4 = parse_number(str_replace(jspsych_files_exp4[2:length(jspsych_files_exp4)], "data/exp4/",""))
subject_mapping_exp4 <- data.frame(old_subject = as.character(seq(1, length(subject_numbers_exp4))), new_subject = subject_numbers_exp4)
jspsych_df_exp4 <- map_dfr(jspsych_list_exp4, ~ .x, .id = 'subjectid') %>% mutate(experiment = 4) %>% 
  left_join(subject_mapping_exp4, by = c("subjectid" = "old_subject")) %>% select(-subjectid) %>% rename(subjectid = new_subject)


jspsych_files_exp5 <- list.files("data/exp5", full.names = T) 
jspsych_list_exp5 <- lapply(jspsych_files_exp5[2:length(jspsych_files_exp5)], read.csv)
jspsych_list_exp5 <- lapply(jspsych_list_exp5, function(x) {x['success'] = NULL; x})
subject_numbers_exp5 = parse_number(str_replace(jspsych_files_exp5[2:length(jspsych_files_exp5)], "data/exp5/",""))
subject_mapping_exp5 <- data.frame(old_subject = as.character(seq(1, length(subject_numbers_exp5))), new_subject = subject_numbers_exp5)
jspsych_df_exp5 <- map_dfr(jspsych_list_exp5, ~ .x, .id = 'subjectid') %>% mutate(experiment = 5) %>% 
  left_join(subject_mapping_exp5, by = c("subjectid" = "old_subject")) %>% select(-subjectid) %>% rename(subjectid = new_subject)

trial_df = rbind(jspsych_df_exp3,jspsych_df_exp4, jspsych_df_exp5) %>% filter(stimulus_type == 'trial') %>% 
  mutate(stimulus_displayed = str_replace(stimulus_displayed, 'stimuli/images/unity_stims/unitystims_', "")) %>% select(-c(subject_num)) %>% rename(block_num = block_number, subject_num = subjectid) %>%
  mutate(subject_num = as.numeric(subject_num)) %>% separate(stimulus_displayed, sep = '_', into = c("animal_pair", 'orientation', 'fam','block_type','pair_counterbalancing', 'junk')) %>% mutate(
    animal_pair = as.numeric(animal_pair), pair_counterbalancing = as.numeric(pair_counterbalancing)) %>%
  select(subject_num, block_num, experiment, animal_pair, "orientation", 'pair_counterbalancing')

consent_df_exp4 <- jspsych_df_exp4 %>% filter(nchar(response) > 5) %>% select(subjectid, response) %>% 
  mutate(consent_level = case_when(str_detect(response, 'Private') ~ 'private', 
                                   str_detect(response, 'Scientific') ~ 'scientific',
                                   str_detect(response, 'General Public') ~ 'public'))

consent_df_exp5 <- jspsych_df_exp5 %>% filter(nchar(response) > 5) %>% select(subjectid, response) %>% 
  mutate(consent_level = case_when(str_detect(response, 'Private') ~ 'private', 
                                   str_detect(response, 'Scientific') ~ 'scientific',
                                   str_detect(response, 'General Public') ~ 'public'))

```

Exclusions
```{r}

# preallocate exclude from output
data_df %<>% mutate(exclude = as.logical(Trials.excludeTrial))

# drop na from exclusions
for (x in 1:nrow(exclusions_df)){
  exclusion_info = exclusions_df[x,]
  
  # need to add 0 for for subject numbers < 10
  if (x < 10) {
    extra_str = "0"
  }
  else {extra_str = ""}
  
  if (exclusion_info$onwards){   # if onwards = T, then remove all trials starting from that trial onwards
      data_df %<>% mutate(
      exclude = case_when(
                        experiment == exclusion_info$experiment & 
                  subject_num == paste0("PKBB_", extra_str, exclusion_info$subject_number) & 
                  block_num >= exclusion_info$trial_number ~ T,
            TRUE ~ exclude))
    
  }
  else {  # if onwards = F, then only mark trial of that number
    data_df %<>% mutate(
      exclude = case_when(
                        experiment == exclusion_info$experiment & 
                  subject_num == paste0("PKBB_", extra_str, exclusion_info$subject_number) & 
                  block_num == exclusion_info$trial_number ~ T,
            TRUE ~ exclude))
    
  
  }
}

# merge with stim info

data_df <- data_df %>% mutate(subject_num = parse_number(subject_num)) %>% left_join(trial_df, by = c('subject_num','block_num','experiment')) %>% mutate(animal = 
  case_when(pair_counterbalancing == 1 ~ 1 + (animal_pair-1) * 2,
            pair_counterbalancing == 2 ~ 2 + (animal_pair-1) * 2)) %>%
  mutate(animal = case_when(test_type == 'nov' & fam_or_test == 'test' & mod(animal,2) == 1 ~ animal + 1,
                            test_type == 'nov' & fam_or_test == 'test' & mod(animal,2) == 0 ~ animal - 1,
                             TRUE ~ animal))

         
write.csv(data_df %>% mutate(experiment = case_when(experiment == 3 ~ 'A', experiment == 4 ~ 'B', experiment == 5 ~ 'C')) %>% select(experiment, fam_or_test, subject_num, block_num, test_type, fam_duration, LT, exclude, age, sex), 'infant_processed_data.csv')

```


Auxiliary analyses
```{r}

## Baseline interest by species

# O fam

ggplot(data_df %>% mutate(animal = factor(animal, levels = c(1,2,3,4,5,6,7,8,9,10,11,12))) %>% filter(fam_or_test == 'test', fam_duration == 0, !exclude), aes(x=animal, y=LT)) + geom_point(alpha=0.2, position = position_dodge(width = .1)) + xlab('Animal') + ylab("LT") + stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .1)) + stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = .1)) + theme_classic(base_size = 20) + theme(legend.position = "none") + ggtitle('0 fam trials')

# all trial

ggplot(data_df %>% mutate(animal = factor(animal, levels = c(1,2,3,4,5,6,7,8,9,10,11,12))) %>% filter(fam_or_test == 'test', !exclude), aes(x=animal, y=LT)) + geom_point(alpha=0.2, position = position_dodge(width = .1)) + xlab('Animal') + ylab("LT") + stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .1)) + stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = .1)) + theme_classic(base_size = 20)  + ggtitle('across test trials') 


## Block number effect
ggplot(data_df %>% filter(fam_or_test == 'test', !exclude, LT > 2), aes(x=block_num, y=LT)) + geom_point(alpha=0.2) + stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = 1), size = 1) + xlab('fam duration') + ylab('LT in s') + labs(color = 'Test type') + theme_classic(base_size = 25) + theme(strip.text.x = element_text(size = 20, colour = "black")) + scale_x_continuous(breaks = c(1,2,3,4,6,8,9)) + scale_color_manual(values = c("grey", "blue", "red")) + geom_smooth()



```
Combined plots
```{r}

median_age = data_df %>% group_by(subject_num) %>% summarize(age = mean(age)) %>% pull(age) %>%median() 


# fot his plot, don't distinguish between background & deviant on 0 fam trials
plot_df = data_df %>% mutate(test_type = case_when(fam_duration == 0 ~ 'baseline', TRUE ~ test_type),
                             age_category = if_else(age < median_age, 'young','old'),
                             age_category = factor(age_category, levels=c('young','old')))


## Exposure duration x test trial
ggplot(plot_df %>% filter(fam_or_test == 'test', !exclude, LT > 2), aes(x=as.numeric(fam_duration), y=LT, group=test_type, color = test_type)) + geom_point(alpha=0.1, size = 2, position = position_jitterdodge(jitter.width = 0.15)) + stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = 1), size = 1) + xlab('fam duration') + ylab('LT in s') + labs(color = 'Test type') + theme_classic(base_size = 25) + theme(strip.text.x = element_text(size = 20, colour = "black")) + scale_x_continuous(breaks = c(1,2,3,4,6,8,9)) + scale_color_manual(values = c("grey", "blue", "red")) + geom_smooth(method ="lm", alpha = 0.4) + geom_hline(yintercept = plot_df %>% dplyr::filter(fam_or_test == 'test', !exclude, test_type == 'baseline') %>% pull(LT) %>% mean(), linetype = "dashed") + coord_trans(y = "log10")

```

Within subject main effect
```{r}

plot_df %>% dplyr::filter(fam_or_test == 'test', !exclude, test_type == 'fam', fam_duration == 8) %>% mean(LT) 

ggplot(plot_df %>% filter(fam_or_test == 'test', !exclude), aes(x=block_num, y=log(LT))) + stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = 1), size = 1) + xlab('block number') + geom_smooth() + ylab('LT in log s') + labs(color = 'Test type') + theme_classic(base_size = 25)

data_df_wide <- data_df %>% filter(fam_or_test == 'test', fam_duration>0,!exclude) 
data_df_wide$fam_test <- paste(data_df_wide$test_type,data_df_wide$fam_duration, sep = '')
data_df_wide <- data_df_wide %>% select(subject_num, fam_test, LT)
data_df_wide <- pivot_wider(data_df_wide, names_from = fam_test, values_from = LT)
data_df_wide$difference1 <- data_df_wide$nov1 - data_df_wide$fam1
data_df_wide$difference2 <- data_df_wide$nov2 - data_df_wide$fam2
data_df_wide$difference3 <- data_df_wide$nov3 - data_df_wide$fam3
data_df_wide$difference4 <- data_df_wide$nov4 - data_df_wide$fam4
data_df_wide$difference6 <- data_df_wide$nov6 - data_df_wide$fam6
data_df_wide$difference8 <- data_df_wide$nov8 - data_df_wide$fam8
data_df_wide$difference9 <- data_df_wide$nov9 - data_df_wide$fam9
data_df_wide <- data_df_wide %>% select(subject_num, difference1, difference2, difference3, difference4, difference6, difference8,difference9)
data_df_wide <- pivot_longer(data_df_wide, cols = c(difference1, difference2, difference3, difference4, difference6, difference8,difference9), names_to = 'type', values_to = 'difference')
data_df_wide$type <- substr(data_df_wide$type, nchar(data_df_wide$type), nchar(data_df_wide$type))
# fot his plot, don't distinguish between background & deviant on 0 fam trials
plot_df = data_df %>% mutate(test_type = case_when(fam_duration == 0 ~ 'baseline', TRUE ~ test_type))

group.colors <- c(baseline = "#333BFF", fam = "#CC6600", nov ="#9633FF")

#within subjects 
ggplot(data_df_wide %>% filter(type>0), aes(x=as.numeric(type), y=difference))  + geom_abline(intercept = 0,slope=0,linetype='dashed') + 
  stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = .1)) + xlab('Fam duration') + ylab('Novel - Familiar (s)')  + theme_classic(base_size = 22) + 
  theme(strip.text.x = element_text(size = 20, colour = "black")) + scale_x_continuous(breaks = c(1,2,3,4,6,8,9))


```


Test effect of adaptive sampling ("missingness analysis")
```{r}

# number of missing trials per block number
ggplot(plot_df %>% group_by(block_num) %>% summarize(num_excluded = sum(exclude)), aes(x = block_num, y = num_excluded)) + geom_point() + geom_line() + theme_classic(base_size = 20)


# check whether effect is there for block num < 5
ggplot(plot_df %>% filter(fam_or_test == 'test', !exclude, LT > 2), aes(x=as.numeric(fam_duration), y=LT, group=test_type, color = test_type)) + geom_point(alpha=0.1, size = 2, position = position_jitterdodge(jitter.width = 0.15)) + stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = 1), size = 1) + xlab('fam duration') + ylab('LT in s') + labs(color = 'Test type') + theme_classic(base_size = 25) + theme(strip.text.x = element_text(size = 20, colour = "black")) + scale_x_continuous(breaks = c(1,2,3,4,6,8,9)) + scale_color_manual(values = c("grey", "blue", "red")) + geom_smooth(method ="lm", alpha = 0.4) + geom_hline(yintercept = plot_df %>% dplyr::filter(fam_or_test == 'test', !exclude, test_type == 'baseline') %>% pull(LT) %>% mean(), linetype = "dashed") + coord_trans(y = "log10")


# predict missingness?

```


Pre-registered models
```{r}

# exclude stuff invalid trials
data_df %<>% filter(!exclude)

# prepare test df with exclusions
test_df = data_df %>% dplyr::filter(fam_or_test == 'test') %>% 
  dplyr::mutate(fam_duration = as.numeric(fam_duration), 
         test_type = case_when(fam_duration == 0 ~ 'fam', TRUE ~ test_type))

test_df$centered_age = scale(test_df$age)

fam_df = data_df %>% filter(fam_or_test == 'fam') %>% mutate(fam_duration = as.numeric(fam_duration), centered_age = age - (data_df %>% distinct(subject_num, experiment, age) %>% pull(age) %>% mean() ))


mA <- lmer(log(LT) ~ poly(fam_duration,1) * test_type + block_num + (1|animal) + (1 | subject_num), data = test_df)
summary(mA)

m0 <- lmer(log(LT) ~ poly(fam_duration,1) * test_type + centered_age + block_num + (1 | subject_num), data = test_df)
summary(m0)

m <- lmer(log(LT) ~ poly(fam_duration,1) * test_type + block_num + (1 | animal), data = test_df)
summary(m)

# Exp 3

# interaction model
model_1 <- lmer(log(LT) ~ poly(fam_duration,1) * test_type + as.factor(animal) + block_num + (1 | subject_num), data = test_df)
summary(model_1)

model_1a<- lmer(log(LT) ~ poly(fam_duration,1) * test_type +  block_num + (1 | subject_num) + (1|animal), data = test_df)
summary(model_1a)

anova(model_1, model_1a)

# ns. because of non-linear interaction

# dishabituation
model_2 <- lmer(log(LT) ~ test_type + block_num + (1 | subject_num), data = test_df %>% filter(fam_duration >= 8) %>% mutate(fam_duration = scale(fam_duration)))
summary(model_2)

# fam pref (EXPLORATORY)
model_2b <- lmer(log(LT) ~ test_type + trial_num + (1 | subject_num), data = test_df %>% filter(experiment == 3, fam_duration == 4))
summary(model_2b)

# cheked for fam pref, but didn't find

# habituation
model_3 <- lmer(log(LT) ~ fam_duration + trial_num + (1 | subject_num), data = test_df %>% filter(experiment == 3, test_type == 'fam'))
summary(model_3)



# Exp 4

# interaction model
model_1 <- lmer(log(LT) ~ fam_duration *test_type + block_num + (1 | subject_num), data = test_df )
summary(model_1)


# Exp 5
model_1 <- lmer(log(LT) ~ test_type + block_num + (1 | subject_num), data = test_df %>% filter(experiment == 5, fam_duration == 6))
summary(model_1)


# ns. because of non-linear interaction

# dishabituation
model_2 <- lmer(log(LT) ~ test_type + trial_num + (1 | subject_num), data = test_df %>% filter(experiment == 4, fam_duration > 8))
summary(model_2)

# fam pref (EXPLORATORY)
model_2b <- lmer(log(LT) ~ test_type + trial_num + (1 | subject_num), data = test_df %>% filter(experiment == 3, fam_duration == 4))
summary(model_2b)

# cheked for fam pref, but didn't find

# habituation
model_3 <- lmer(log(LT) ~ fam_duration + trial_num + (1 | subject_num), data = test_df %>% filter(experiment == 4, test_type == 'fam'))
summary(model_3)

# check for baseline differences

model_baseline_diffs <- lmer(log(LT) ~ as.factor(animal) + trial_num + background_deviant + (1 | subject_num), data = test_df %>% filter(experiment == 4, test_type == 'fam'))
summary(model_3)

```




