---
title: "violations_gradient"
output: html_document
date: "2023-07-23"
---

```{r}
library(tidyverse)

baby_model_data = read_csv('processed_data/model_data/summarized_results_detailed_new.csv', col_names = c("sub_id", "batch_id", "trial_num", "stim_sequence", "violation", "epsilon","b_val","d_val", "mu_prior", "v_prior", "alpha_prior", "beta_prior", "n_samples"))


```

```{r}

baby_model_data <- baby_model_data %>% mutate(test_type = case_when(str_detect(stim_sequence, 'D') ~ 'deviant', TRUE ~ 'background'), fam_duration = nchar(stim_sequence) - 1)

baby_model_data <- baby_model_data %>% group_by(batch_id, sub_id) %>% slice_tail(n=1)

write_csv(baby_model_data, "processed_data/model_data/sliced_model_data.csv")

ggplot(baby_model_data, aes(x = fam_duration, y = n_samples, group = test_type, color = test_type)) + stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = 0.1), size = 1) + theme_classic(base_size = 15) + xlab('fam duration') + scale_color_manual(values = c("blue", "red")) + facet_wrap(~epsilon)


ggplot(baby_model_data %>% filter(background_seq == 'deviant'), aes(x = stimulus_id, y = n_sample, group = violation_type, color = violation_type)) + geom_line() + geom_point() + theme_classic(base_size = 15) + facet_grid(~ stim_sequence)



```
