---
title: "02_visualization"
author: "anjie"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: yes
    theme: paper
    toc: yes
    toc_float: yes
    
---

```{r}
library(tidyverse)
library(ggthemes)
library(here)





d <- read_csv(here("data/01_trimmed_data/trimmed_lt_d.csv"))

cr_d <- read_csv(here("data/01_trimmed_data/trimmed_complexity_rating.csv"))
sim_d <- read_csv(here("data/01_trimmed_data/trimmed_similarity_rating_df.csv"))
```



# background only blocks 

## everything separate

```{r}
d %>% 
  filter(block_type == "background_block") %>% 
  ggplot(aes(x = trial_number, y = log(total_rt), color = background_type)) + 
   stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
    stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .2)) + 
  theme_few()  + 
  facet_wrap(~total_trial_number)
  
```

## animate vs inanimate 

```{r}
d %>% 
  filter(block_type == "background_block") %>% 
  ggplot(aes(x = trial_number, y = log(total_rt), color = animacy)) + 
   stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
    stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .2)) + 
  theme_few()  + 
  facet_wrap(~total_trial_number)
```

## singleton vs pair 

```{r}
d %>% 
  filter(block_type == "background_block") %>% 
  ggplot(aes(x = trial_number, y = log(total_rt), color = number)) + 
   stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
    stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .2)) + 
  theme_few()  + 
  facet_wrap(~total_trial_number)
```


## left vs right 

```{r}
d %>% 
  filter(block_type == "background_block") %>% 
  ggplot(aes(x = trial_number, y = log(total_rt), color = pose)) + 
   stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
    stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .2)) + 
  theme_few()  + 
  facet_wrap(~total_trial_number)
```


# deviant 

```{r}
d %>% 
   ggplot(aes(x = trial_number, y = log(total_rt), color = trial_type)) + 
   stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
    stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .2)) + 
  theme_few()  + 
  facet_grid(background_type~violation_type)
```

## animate vs inanimate 

```{r}
d %>% 
   ggplot(aes(x = trial_number, y = log(total_rt), color = trial_type)) + 
   stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
    stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .2)) + 
  theme_few()  + 
  facet_grid(animacy~violation_type)
```


## singleton vs pair 

```{r}
d %>% 
   ggplot(aes(x = trial_number, y = log(total_rt), color = trial_type)) + 
   stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
    stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .2)) + 
  theme_few()  + 
  facet_grid(number~violation_type)
```

## left vs right 

```{r}

d %>% 
   ggplot(aes(x = trial_number, y = log(total_rt), color = trial_type)) + 
   stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
    stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .2)) + 
  theme_few()  + 
  facet_grid(pose~violation_type)

```

## assuming background are the same 



```{r}

d %>% 
  mutate(violation_type_with_background = case_when(
    trial_type == "background" ~ "background", 
    TRUE ~ violation_type
  )) %>% 
   ggplot(aes(x = trial_number, y = log(total_rt), color = violation_type_with_background)) + 
   stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
    stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .2)) + 
  theme_few() 

```

```{r}
d %>% 
  mutate(violation_type_with_background = case_when(
    trial_type == "background" ~ "background", 
    TRUE ~ violation_type
  )) %>% 
   ggplot(aes(x = trial_number, y = log(total_rt), color = violation_type_with_background)) + 
   stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
    stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .2)) + 
  facet_wrap(~total_trial_number)+ 
  theme_few()
```


# Complexity rating 

oops 

```{r}
cr_d %>% 
  ggplot(aes(x = complexity_rating_type, y = complexity_rating)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  theme_few() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```


# Similarity rating 

```{r}
sim_d %>% 
  ggplot(aes(x = similarity_rating_violation, y = similarity_rating)) +
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  theme_few()
```


# Item level analysis 

## do we have that much data to tell? 
```{r}
cr_d %>% 
  group_by(complexity_rating_stimulus) %>% 
  count() %>% 
  ggplot(aes(x = n)) +
  geom_histogram()


cr_d %>% 
  group_by(complexity_rating_stimulus) %>% 
  count() %>% 
  ggplot(aes(x = n)) +
  geom_histogram()


sim_d %>% 
  mutate(combined = paste(similarity_rating_background, similarity_rating_deviant, "_")) %>% 
  group_by(combined) %>% 
  count() %>% 
  filter(n > 1)
```



## complexity 

```{r}
multiple_rators_stimulus <- cr_d %>% 
  group_by(complexity_rating_stimulus) %>% 
  count() %>% 
  filter(n > 3) %>% 
  pull(complexity_rating_stimulus)


cr_d %>% 
  filter(complexity_rating_stimulus %in% multiple_rators_stimulus) %>% 
  ggplot(aes(x = complexity_rating_stimulus, y = complexity_rating)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  theme_few() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 



cr_d %>% 
  filter(complexity_rating_stimulus %in% multiple_rators_stimulus) %>% 
  ggplot(aes(x = complexity_rating_stimulus, y = complexity_rating)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  theme_few() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  facet_wrap(~animacy, scales = "free")


cr_d %>% 
  filter(complexity_rating_stimulus %in% multiple_rators_stimulus) %>% 
  ggplot(aes(x = complexity_rating_stimulus, y = complexity_rating)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  theme_few() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  facet_wrap(~number, scales = "free")

cr_d %>% 
  filter(complexity_rating_stimulus %in% multiple_rators_stimulus) %>% 
  ggplot(aes(x = complexity_rating_stimulus, y = complexity_rating)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  theme_few() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  facet_wrap(~pose, scales = "free")
```

## similarity 

```{r}
sim_d %>% 
  mutate(combined = paste(similarity_rating_background, similarity_rating_deviant, "_")) %>% 
  ggplot(aes(x = combined, y = similarity_rating)) +
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  theme_few()

```






