---
title: "noisy_bb_cleaner"
author: "anjie"
date: "5/5/2021"
output: html_document
---

```{r}
library(tidyverse)
library(matrixStats)
library(here)

source(here("adult_modeling/scripts/grid_approximation.R"))
source(here("adult_modeling/scripts/noisy_update.R"))

```

# generate creature sequence 
this is easy fill in later 
```{r}
make_creature <- function(
  total_feature,
  complexity
){
  
}

make_dissimilar_creature <- function(
  creature, 
  dissmilar_ratio, 
){
  
}

generate_creature_sequence <- function(
  block_length, 
  deviant_number, 
  deviant_position, 
){
  
}
```

# generate creature sequence 

```{r}
noisy_observation_feature <- function(
  feature, 
  n_sample, 
  epsilon 
){
  real_features <- rep(feature, n_sample)
  noisy <- rbernoulli(p = epsilon, n = n_sample)
  return(ifelse(noisy, 1-real_features, real_features))
  
}


noisy_observation_creature <- function(
  creature, 
  n_sample, 
  epsilon
){
  sapply(creature, function(y){noisy_observation_feature(
    feature = y, 
    n_sample = n_sample, 
    epsilon = epsilon
  )})
  
}

```

## test creature 
```{r}
test_creature_background_theta <- c(0.2, 0.2, 0.2, 0.8, 0.8, 0.3)
test_creature_deviant_theta <- c(0.2, 0.8, 0.8, 0.2, 0.2, 0.9)
#test creature
# these will be a block [y_1, y_2, y_3, y_4, z_1, y_5]
y_1 <- sapply(test_creature_background_theta, function(x){rbernoulli(p = x, n = 1)})
y_2 <- sapply(test_creature_background_theta, function(x){rbernoulli(p = x, n = 1)})
y_3 <- sapply(test_creature_background_theta, function(x){rbernoulli(p = x, n = 1)})
y_4 <- sapply(test_creature_background_theta, function(x){rbernoulli(p = x, n = 1)})
z_1 <-  sapply(test_creature_deviant_theta, function(x){rbernoulli(p = x, n = 1)})
#y_5 <- sapply(test_creature_background_theta, function(x){rbernoulli(p = x, n = 1)})

# in each trial collects like 100 times
y_1_noisy_observation <- rbind(noisy_observation_creature(y_1, 5000, 0.2))
y_2_noisy_observation <- rbind(noisy_observation_creature(y_2, 5000, 0.2))
y_3_noisy_observation <-  rbind(noisy_observation_creature(y_3, 5000, 0.2))
y_4_noisy_observation <-  rbind(noisy_observation_creature(y_4, 100, 0.2))
z_1_noisy_observation <-  rbind(noisy_observation_creature(z_1, 100, 0.2))



```


```{r}
grid_theta <- seq(0.1, 0.9, 0.05)
grid_epsilon <- seq(0.1, 0.9, 0.05)


post_first_update_theta_approx <- grid_approximate_creature_with_theta_initial(
  grid_theta = grid_theta, 
  grid_epsilon = grid_epsilon, 
  noisy_creature_observation = y_1_noisy_observation, 
  alpha_prior = 1, 
  beta_prior = 1,
  alpha_epsilon = 10, 
  beta_epsilon = 1
)


post_first_update_theta_epsilon_approx <- grid_approximate_creature_with_theta_and_epsilon_initial(
  grid_theta = grid_theta, 
  grid_epsilon = grid_epsilon, 
  noisy_creature_observation = y_1_noisy_observation, 
  alpha_prior = 1, 
  beta_prior = 1,
  alpha_epsilon = 10, 
  beta_epsilon = 1
)

post_first_update_theta_approx
post_first_update_theta_epsilon_approx
```




```{r}
post_second_update_theta_approx <- grid_approximate_creature_with_theta_continuous(
  grid_theta = grid_theta, 
  grid_epsilon = grid_epsilon, 
  noisy_creature_observation = y_2_noisy_observation,  
  updated_posterior_df = post_first_update_theta_approx,
  alpha_epsilon = 10, 
  beta_epsilon = 1
)

# current having weird issue around 0.1; R refuses to recognize it is there
# leading to weird issue related to log probablity having numeric(0) and problem with normalizing 
post_second_update_theta_epsilon_approx <- grid_approximate_creature_with_theta_and_epsilon_continuous(
  grid_theta = grid_theta, 
  grid_epsilon = grid_epsilon, 
  noisy_creature_observation = y_2_noisy_observation,  
  updated_posterior_df = post_first_update_theta_approx,
  alpha_epsilon = 10, 
  beta_epsilon = 1
)
```

check if we are actually doing anything meaningful: 

```{r}
test_creature_background_theta <- c(0.2, 0.2, 0.2, 0.8, 0.8, 0.3)

first_update <- post_first_update_theta_approx %>% 
  mutate(update_number = 1)
second_update <- post_second_update_theta_approx %>% 
  mutate(update_number = 2)

two_updates <- bind_rows(first_update, second_update)

two_updates %>% 
  ggplot(aes(x = theta, 
             y = normalized_log_posterior, 
             color = update_number)) + 
  geom_point()+
  facet_wrap(~feature_index)
```
actually not entirely sure. probably because we are not approximating over epsilon as well? anyway we can try to do this one more time

```{r}


post_third_update_theta_approx <- grid_approximate_creature_with_theta_continuous(
  grid_theta = grid_theta, 
  grid_epsilon = grid_epsilon, 
  noisy_creature_observation = y_3_noisy_observation,  
  updated_posterior_df = post_second_update_theta_approx,
  alpha_epsilon = 10, 
  beta_epsilon = 1
) %>% 
  mutate(update_number = 3)


three_updates <- bind_rows(two_updates, post_third_update_theta_approx)


three_updates %>% 
  ggplot(aes(x = theta, 
             y = normalized_log_posterior, 
             color = update_number)) + 
  geom_point()+
  facet_wrap(~feature_index)

```

maybe? not entirely sure. 

