---
title: "02_visualization"
output: html_document
date: "`r Sys.Date()`"
---


```{r}
library(tidyverse)
library(here)
library(magrittr)
library(jsonlite)
library(ggthemes)

cr <- read_csv(here("data/complexity_rating.csv")) %>% mutate(complexity_rating = complexity_rating + 1)
sr <- read_csv(here("data/similarity_rating.csv"))
em <- read_csv(here("data/adult_norming_embeddings.csv"))

c_dis <- read_csv(here("data/eucledian_distances_adultnorming.csv"))
e_dis <- read_csv(here("data/cosine_distances_adultnorming.csv"))
```

```{r}
cr %>% distinct(subject) %>% count()
sr %>% distinct(subject) %>% count()

```



# Complexity rating 

```{r}
cr %>% 
  ggplot(aes(x = rating_animacy, y = complexity_rating)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  ylim(0, 7) + 
  theme_few() 


cr %>% 
  ggplot(aes(x = rating_pose, y = complexity_rating)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
    ylim(0, 7) + 
  theme_few() 


cr %>% 
  ggplot(aes(x = rating_number, y = complexity_rating)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  ylim(0, 7) + 
  theme_few() 


```

```{r}
cr %>% 
  ggplot(aes(x = rating_animacy, y = complexity_rating, color = rating_number)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  ylim(0, 7) + 
  theme_few()  + 
  facet_wrap(~rating_pose)

```



```{r}
cr %>% 
   ggplot(aes(x = rating_stimulus, y = complexity_rating)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  theme_few() + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
```


```{r}
cr %>% 
  mutate(stim_name = gsub("media/stimuli/","",  rating_stimulus)) %>% 
  left_join(em, by = "stim_name") %>% 
  pivot_longer(cols = c("V1", "V2"), 
               names_to = "embedding_dim", 
               values_to = "embedding_val") %>% 
  ggplot(aes(x = embedding_val, y = complexity_rating, color = rating_animacy)) + 
  geom_point(alpha = .3, position = position_jitter(width = .2)) + 
  #geom_smooth(method = "lm") + 
  facet_wrap(~embedding_dim) + theme_few()
```



```{r}
cr %>% 
  mutate(stim_name = gsub("media/stimuli/","",  rating_stimulus)) %>% 
  group_by(rating_stimulus) %>% 
  summarise(mean_complexity_rating = mean(complexity_rating)) %>% 
   mutate(stim_name = gsub("media/stimuli/","",  rating_stimulus)) %>% 
  left_join(em, by = "stim_name") %>% 
  mutate(rating_animacy = ifelse(grepl("inanimate", stim_name), "inanimate", "animate")) %>% 
  pivot_longer(cols = c("V1", "V2"), 
               names_to = "embedding_dim", 
               values_to = "embedding_val") %>% 
  ggplot(aes(x = embedding_val, y = mean_complexity_rating, color = rating_animacy)) + 
  geom_point(alpha = .3, position = position_jitter(width = .2)) + 
  geom_smooth(method = "lm") + 
  facet_wrap(~embedding_dim) + theme_few()
```



# Similarity 

```{r}
sr %>% 
  group_by(subject) %>% 
  count() %>% 
  rename(n_trial = n) %>% 
  left_join(sr, by = "subject") %>% 
  group_by(subject, n_trial, chosen_violation) %>% 
  count() %>% 
  filter(!is.na(chosen_violation)) %>%
  mutate(proportion = n / n_trial) %>% 
  ggplot(aes(x = chosen_violation, y = proportion)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  theme_few() 
```


```{r}
sr %>% 
  mutate(unchosen_violation = case_when(
    left_violation == chosen_violation ~ right_violation, 
    right_violation == chosen_violation ~ left_violation
  )) %>% 
  left_join(sr %>% group_by(subject, chosen_violation) %>% count() %>% rename(total_n_in_cateogry = n), by = c("subject", "chosen_violation")) %>% 
  group_by(subject, chosen_violation, total_n_in_cateogry) %>% 
  count(unchosen_violation) %>% 
  mutate(proportion = n / total_n_in_cateogry) %>% 
  filter(!is.na(chosen_violation)) %>%
  ggplot(aes(x = unchosen_violation, y = proportion)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  facet_wrap(~chosen_violation) + 
  theme_few()
```


# basic 

```{r}

summary_sr <- sr %>% 
  summarise(
    median = median(rt), 
    mad = mad(rt), 
  ) %>% 
  mutate( upper = median + 3 * mad)


clean_sr = sr %>% 
  filter(rt < summary_sr$upper)


clean_sr  %<>% mutate(
    violation_type = case_when(
      (left_violation == "animacy" & right_violation == "identity") | (left_violation == "identity" & right_violation == "animacy") ~ "animacy_identity", 
      (left_violation == "animacy" & right_violation == "pose") | (left_violation == "pose" & right_violation == "animacy") ~ "animacy_pose", 
      (left_violation == "identity" & right_violation == "pose") | (left_violation == "pose" & right_violation == "identity") ~ "identity_pose", 
      (left_violation == "animacy" & right_violation == "number") | (left_violation == "number" & right_violation == "animacy") ~ "animacy_number", 
      (left_violation == "identity" & right_violation == "number") | (left_violation == "number" & right_violation == "identity") ~ "identity_number", 
      (left_violation == "pose" & right_violation == "number") | (left_violation == "number" & right_violation == "pose") ~ "pose_number", 
    )
  ) 
```


## proportion 

```{r}
subject_n_trial_per_category <- clean_sr %>% 
  group_by(subject, violation_type) %>% 
  count() %>% 
  rename(total_trial = n)

summarised_proportion <- clean_sr %>% 
  group_by(subject, violation_type, chosen_violation) %>% 
  count() %>% 
  left_join(subject_n_trial_per_category %>% ungroup(), by = c("subject", "violation_type")) %>% 
  mutate(p = n / total_trial) %>% 
  ungroup() %>% 
  complete(
    subject,
    nesting(violation_type, chosen_violation),
    fill = list(n = 0, p = 0),
    explicit = FALSE
  ) 
  

max_p_df <- summarised_proportion %>% 
  group_by(violation_type, chosen_violation) %>% 
  summarise(mean = mean(p)) %>% 
  filter(mean == max(mean))
  

sim_plot <- summarised_proportion %>% 
  filter(
    (violation_type == "animacy_identity" & chosen_violation == "identity") | 
   (violation_type == "animacy_number" & chosen_violation == "number") | 
    (violation_type == "animacy_pose" & chosen_violation == "pose")| 
    (violation_type == "identity_number" & chosen_violation == "number") | 
    (violation_type == "identity_pose" & chosen_violation == "pose") |
    (violation_type == "pose_number" & chosen_violation == "pose")
  ) %>% 
  ggplot(aes(x = violation_type, y = p, color = chosen_violation)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  ylim(0, 1) + 
  theme_few() + 
  theme(axis.text.x = element_blank()) + 
  xlab("") 
```




```{r}
rt_plot <- clean_sr %>% 
  ggplot(aes(x = violation_type, y = log(rt))) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  theme_few() + 
  theme_few() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  xlab("")
```


```{r}
library(patchwork)

sim_plot / rt_plot
```



```{r}
sr %>% 
  group_by(subject, chosen_violation) %>% 
  summarise(m_rt = mean(rt)) %>% 
  filter(!is.na(chosen_violation)) %>%
  ggplot(aes(x = chosen_violation, y = m_rt)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 
  theme_few() 
```

