---
title: "03_embedding_dis"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
library(tidyverse)
library(here)
library(jsonlite)
library(ggthemes)

cr <- read_csv(here("data/complexity_rating.csv")) %>% mutate(complexity_rating = complexity_rating + 1)
sr <- read_csv(here("data/similarity_rating.csv"))
em <- read_csv(here("data/adult_norming_embeddings.csv"))

e_dis <- read_csv(here("data/eucledian_distances_with_number.csv")) %>% rename(stim_name = `...1`)
c_dis <- read_csv(here("data/cosine_distances_with_number.csv"))%>% rename(stim_name = `...1`)


proportion_ds <- read_csv(here("data/em_dis_with_pair.csv"))


replace_name <- function(x) gsub("media/stimuli/", "", x)
clean_sr <- sr %>% 
  mutate_at(c("target", "left", "right"), replace_name) #%>% 
  #filter(!left_violation == "number", !right_violation == "number")
```



## get the distinct triad and find the embedding distance value matching to it 

time consuming, should read directly 

```{r}


triad <- clean_sr %>% 
  distinct(target, left, right, target_number, left_violation, right_violation) %>% 
  filter(!is.na(target), !is.na(left), !is.na(right)) %>% 
  rowwise() %>% 
  mutate(left_number = case_when(
    target_number == "pair" && left_violation == "number" ~ "single", 
    target_number == "pair" && left_violation != "number" ~ "pair", 
    target_number == "single" && left_violation == "number" ~ "pair", 
    target_number == "single"&& left_violation != "number" ~ "single"
   ), 
   right_number = case_when(
    target_number == "pair" && right_violation == "number" ~ "single", 
    target_number == "pair" && right_violation != "number" ~ "pair", 
    target_number == "single" && right_violation == "number" ~ "pair", 
    target_number == "single"&& right_violation != "number" ~ "single"
   )
   )%>% 
  select(target, left, right, target_number, left_number, right_number) %>% 
  mutate(
    target_match_name = case_when(
      target_number == "pair" ~ gsub("(.*)(\\.)", paste0("\\1_pair\\2"), target), 
      TRUE ~ target
    ), 
    left_match_name = case_when(
      left_number == "pair" ~ gsub("(.*)(\\.)", paste0("\\1_pair\\2"), left), 
      TRUE ~ left
    ), 
    right_match_name = case_when(
      right_number == "pair" ~ gsub("(.*)(\\.)", paste0("\\1_pair\\2"), right), 
      TRUE ~ right
    )
  )


get_distance <- function(stim_a_name, stim_b_name,  dist){
  
  tibble("val" = dist %>%
  filter(stim_name == {{stim_b_name}}) %>% 
  select({{stim_a_name}}) %>% 
  pull())
  
}

triad_ds <- triad %>% 
  ungroup() %>% 
  mutate(left_eds = map2_df(.x = triad$target_match_name, .y = triad$left_match_name, .f = get_distance, e_dis), 
         right_eds = map2_df(.x = triad$target_match_name, .y = triad$right_match_name, .f = get_distance, e_dis))


proportion_ds <- triad_ds %>% 
  unnest(left_eds,right_eds) %>% 
  rename(left_eds = val, 
         right_eds = val1) %>% 
  #filter(target != left, target != right) %>% 
  mutate(
    left_p_eds = left_eds / (left_eds + right_eds), 
    right_p_eds = right_eds / (left_eds + right_eds)
  )

write_csv(proportion_ds, here("data/em_dis_with_pair.csv"))

```

# total plot 


```{r}
# calculate violation proportion
ds_proportion_df <- clean_sr %>% 
  filter(!is.na(target), !is.na(left), !is.na(right)) %>% 
  rowwise() %>% 
  mutate(left_number = case_when(
    target_number == "pair" && left_violation == "number" ~ "single", 
    target_number == "pair" && left_violation != "number" ~ "pair", 
    target_number == "single" && left_violation == "number" ~ "pair", 
    target_number == "single"&& left_violation != "number" ~ "single"
   ), 
   right_number = case_when(
    target_number == "pair" && right_violation == "number" ~ "single", 
    target_number == "pair" && right_violation != "number" ~ "pair", 
    target_number == "single" && right_violation == "number" ~ "pair", 
    target_number == "single"&& right_violation != "number" ~ "single"
   )
   )%>% 
  mutate(
    target_match_name = case_when(
      target_number == "pair" ~ gsub("(.*)(\\.)", paste0("\\1_pair\\2"), target), 
      TRUE ~ target
    ), 
    left_match_name = case_when(
      left_number == "pair" ~ gsub("(.*)(\\.)", paste0("\\1_pair\\2"), left), 
      TRUE ~ left
    ), 
    right_match_name = case_when(
      right_number == "pair" ~ gsub("(.*)(\\.)", paste0("\\1_pair\\2"), right), 
      TRUE ~ right
    )
  ) %>% left_join(proportion_ds %>% select(target_match_name, left_match_name, right_match_name, 
                                           left_eds, right_eds, left_p_eds, right_p_eds), 
                  by = c("target_match_name", "left_match_name", "right_match_name")) %>% 
  filter(!is.na(left_eds)) %>% 
  mutate(
    choose_left_or_right = if_else(chosen_violation == left_violation, 
                                   "left", 
                                   "right"), 
    chosen_eds = if_else(choose_left_or_right == "left", left_p_eds, right_p_eds), 
    unchosen_eds =   if_else(choose_left_or_right == "right",  left_p_eds, right_p_eds), 
  ) %>% 
  select(subject, target, left_violation, right_violation, chosen_violation, unchosen_eds) %>% 
  pivot_longer(cols = c("unchosen_eds"), 
               names_to = "proportion_type", 
               values_to = "proportion") #%>% 
  #rowwise() %>% 
  #mutate(choose_this = generate(dist_bernoulli(proportion), 1)[[1]])


```





# Similarity judgment 


```{r}
clean_sr_cateogry <- clean_sr %>% 
  mutate(
    violation_type = case_when(
      (left_violation == "animacy" & right_violation == "identity") | (left_violation == "identity" & right_violation == "animacy") ~ "animacy_identity", 
      (left_violation == "animacy" & right_violation == "pose") | (left_violation == "pose" & right_violation == "animacy") ~ "animacy_pose", 
      (left_violation == "identity" & right_violation == "pose") | (left_violation == "pose" & right_violation == "identity") ~ "identity_pose", 
      (left_violation == "identity" & right_violation == "number") | (left_violation == "number" & right_violation == "identity") ~ "identity_number",
      (left_violation == "pose" & right_violation == "number") | (left_violation == "number" & right_violation == "pose") ~ "pose_number",
      (left_violation == "animacy" & right_violation == "number") | (left_violation == "number" & right_violation == "animacy") ~ "animacy_number"
    )
  ) 


sim_judg_plot <- clean_sr_cateogry %>% 
  left_join(
    clean_sr_cateogry %>% group_by(subject, violation_type) %>% count() %>% rename(total_trial = n), 
    by = c("subject", "violation_type")
  ) %>% 
  group_by(subject, violation_type, total_trial, chosen_violation) %>% 
  count() %>% 
  mutate(p = n / total_trial ) %>% 
  ungroup() %>% 
  complete(
    subject,
    nesting(violation_type, chosen_violation),
    fill = list(n = 0, p = 0, total_trial = 24),
    explicit = FALSE
  ) %>% 
  ggplot(aes(x = chosen_violation, y = p)) + 
  stat_summary(fun.data = "mean_cl_boot") + 
  facet_wrap(~violation_type, scales = "free_x") + 
  theme_few()

sim_judg_plot
```


# Embedding 

```{r}
ds_proportion_df %>% 
   mutate(
    violation_type = case_when(
      (left_violation == "animacy" & right_violation == "identity") | (left_violation == "identity" & right_violation == "animacy") ~ "animacy_identity", 
      (left_violation == "animacy" & right_violation == "pose") | (left_violation == "pose" & right_violation == "animacy") ~ "animacy_pose", 
      (left_violation == "identity" & right_violation == "pose") | (left_violation == "pose" & right_violation == "identity") ~ "identity_pose", 
      (left_violation == "identity" & right_violation == "number") | (left_violation == "number" & right_violation == "identity") ~ "identity_number",
      (left_violation == "pose" & right_violation == "number") | (left_violation == "number" & right_violation == "pose") ~ "pose_number",
      (left_violation == "animacy" & right_violation == "number") | (left_violation == "number" & right_violation == "animacy") ~ "animacy_number"
    )
  ) %>% 
  ggplot(aes(x = chosen_violation, y = proportion)) + 
  stat_summary(fun.data = "mean_cl_boot") + 
  facet_wrap(~violation_type, scales = "free_x") + 
  theme_few()
```



```{r}
choice_p_df <- bind_rows(identity_full_p_df, pose_full_p_df, animacy_full_p_df) %>% 
  mutate(
    violation_type = case_when(
      (category == "animacy" & violation_type == "identity") | (category == "identity" & violation_type == "category") ~ "animacy_identity", 
      (category == "animacy" & violation_type == "pose") | (category == "pose" & violation_type == "animacy") ~ "animacy_pose", 
      (category == "identity" & violation_type == "pose") | (category == "pose" & violation_type == "identity") ~ "identity_pose"
    )
  ) %>% 
  filter(!is.na(violation_type)) %>% 
  rowwise() %>% 
  mutate(choose_this = distributional::generate(distributional::dist_bernoulli(p), 1)[[1]])
  

```

```{r}
choice_p_df %<>%
  mutate(chosen_category = case_when(
    choose_this ~ category, 
    !choose_this & violation_type == "animacy_identity" & category == "animacy" ~ "identity", 
    !choose_this & violation_type == "animacy_identity" & category == "identity" ~ "animacy", 
    !choose_this & violation_type == "identity_pose" & category == "identity" ~ "pose", 
    !choose_this & violation_type == "identity_pose" & category == "pose" ~ "identity", 
    !choose_this & violation_type == "animacy_pose" & category == "animacy" ~ "pose", 
    !choose_this & violation_type == "animacy_pose" & category == "pose" ~ "animacy", 
  ))
```

```{r}
choice_p_df %>% 
  select(violation_type, category, proportion_type, chosen_category)  

```


```{r}
plot_df <- choice_p_df %>% 
  select(violation_type,  proportion_type, chosen_category)  %>% 
  left_join(
    choice_p_df %>% 
  group_by(violation_type, proportion_type) %>% 
  count() %>% rename(total_trial = n), 
  by = c("violation_type", "proportion_type")
  ) %>% 
  group_by(chosen_category, violation_type, proportion_type, total_trial) %>% 
  count() %>% 
  filter(proportion_type == "eds_p_for_choice")





embedding_plot <- plot_df %>%  
  ungroup() %>% 
  ggplot(aes(x = chosen_category, y = n / total_trial, color = proportion_type)) + 
  geom_point() + 
  facet_wrap(~violation_type, scales = "free_x") + 
  ylim(0, 1) + 
  theme_few()+ 
  theme(legend.position = "None") + 
  xlab("")


```



```{r}
clean_sr_cateogry %>% 
  left_join(
    clean_sr_cateogry %>% group_by(subject, violation_type) %>% count() %>% rename(total_trial = n), 
    by = c("subject", "violation_type")
  ) %>% 
  group_by(subject, violation_type, total_trial, chosen_violation) %>% 
  count() %>% 
  mutate(p = n / total_trial ) %>% 
  ungroup() %>% 
  complete(
    subject,
    nesting(violation_type, chosen_violation),
    fill = list(n = 0, p = 0, total_trial = 24),
    explicit = FALSE
  ) %>% 
  s
```



```{r}
library(patchwork)
embedding_plot  / sim_judg_plot
```



# RT and similarity 


```{r}



summary_sr <- clean_sr %>% 
  summarise(
    median = median(rt), 
    mad = mad(rt), 
  ) %>% 
  mutate( upper = median + 3 * mad)


clean_sr = clean_sr %>% 
  filter(rt < summary_sr$upper)



ds_proportion_df %>% 
  mutate(dist_diff = (abs(left_p_eds - right_p_eds) / (left_p_eds + right_p_eds))) %>% 
  mutate(
    violation_type = case_when(
      (left_violation == "animacy" & right_violation == "identity") | (left_violation == "identity" & right_violation == "animacy") ~ "animacy_identity", 
      (left_violation == "animacy" & right_violation == "pose") | (left_violation == "pose" & right_violation == "animacy") ~ "animacy_pose", 
      (left_violation == "identity" & right_violation == "pose") | (left_violation == "pose" & right_violation == "identity") ~ "identity_pose",
      (left_violation == "identity" & right_violation == "number") | (left_violation == "number" & right_violation == "identity") ~ "identity_number",
      (left_violation == "pose" & right_violation == "number") | (left_violation == "number" & right_violation == "pose") ~ "pose_number",
      (left_violation == "animacy" & right_violation == "number") | (left_violation == "number" & right_violation == "animacy") ~ "animacy_number"
    )
  ) %>% 
  select(subject, left_violation, right_violation, dist_diff, violation_type) %>% 
  left_join(clean_sr, by = c("subject", "left_violation", "right_violation")) %>% 
  ggplot(aes(x = dist_diff, y = log(rt), color = violation_type)) + 
  geom_point(alpha = .1) + 
  geom_smooth(method = "lm")

```

